<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="dbetabinom" timestamp="2023-10-11T13:22:31Z" hostname="c292e1af1db4" tests="13" skipped="0" failures="0" errors="0" time="0.304">
    <testcase time="0.044" classname="dbetabinom" name="dbetabinom_for_every_x_support_is_between_0_and_1"/>
    <testcase time="0.08" classname="dbetabinom" name="sum_of_the_dbetabinom_values_over_the_whole_support_for_x_is_1"/>
    <testcase time="0.0219999999999999" classname="dbetabinom" name="dbetabinom_gives_correct_numeric_result"/>
    <testcase time="0.00900000000000001" classname="dbetabinom" name="dbetabinomMix_gives_a_result_between_0_and_1"/>
    <testcase time="0.00900000000000001" classname="dbetabinom" name="dbetabinomMix_gives_the_correct_numeric_result"/>
    <testcase time="0.01" classname="dbetabinom" name="Sum_of_dbetabinomMix_for_all_x_is_1"/>
    <testcase time="0.00900000000000001" classname="dbetabinom" name="dbetabinomMix_gives_the_correct_numeric_result"/>
    <testcase time="0.00900000000000001" classname="dbetabinom" name="The_pbetaMix_has_incrementally_higher_cdf_with_increase_x_support"/>
    <testcase time="0.01" classname="dbetabinom" name="pbetaMix_gives_the_correct_number_result"/>
    <testcase time="0.00800000000000001" classname="dbetabinom" name="The_complement_of_pbetaMix_can_be_derived_with_a_different_lower.tail_flag"/>
    <testcase time="0.011" classname="dbetabinom" name="qbetaMix_gives_the_correct_number_result"/>
    <testcase time="0.01" classname="dbetabinom" name="qbetaMix_gives_the_correct_number_result"/>
    <testcase time="0.073" classname="dbetabinom" name="qbetaMix_gives_a_number_result"/>
  </testsuite>
  <testsuite name="helpers" timestamp="2023-10-11T13:22:31Z" hostname="c292e1af1db4" tests="4" skipped="0" failures="0" errors="0" time="0.035">
    <testcase time="0.017" classname="helpers" name="logit_works_as_expected"/>
    <testcase time="0.005" classname="helpers" name="logit_works_as_expected"/>
    <testcase time="0.004" classname="helpers" name="logit_works_as_expected"/>
    <testcase time="0.00900000000000001" classname="helpers" name="logit_gives_expected_value_for_example_value_0.2"/>
  </testsuite>
  <testsuite name="ocPostprob" timestamp="2023-10-11T13:22:31Z" hostname="c292e1af1db4" tests="18" skipped="0" failures="1" errors="3" time="97.277">
    <testcase time="0.022" classname="ocPostprob" name="h_get_distance_gives_an_error_with_one_element_numeric"/>
    <testcase time="0.00600000000000001" classname="ocPostprob" name="h_get_distance_gives_results_within_range"/>
    <testcase time="0.019" classname="ocPostprob" name="h_get_distance_gives_an_error_with_non_sorted_argument"/>
    <testcase time="0.013" classname="ocPostprob" name="h_get_looks_gives_correct_results_if_input_is_identical">
      <error type="error" message="Error in `get_looks(dist = dist, nnE = c(10, 20, 30), nnF = c(10, 20, 30))`: could not find function &quot;get_looks&quot; ('test-ocPostprob.R:21:3')">Error in `get_looks(dist = dist, nnE = c(10, 20, 30), nnF = c(10, 20, 30))`: could not find function "get_looks"</error>
    </testcase>
    <testcase time="0.0349999999999999" classname="ocPostprob" name="get_looks_gives_correct_results_if_input_is_identical">
      <error type="error" message="Error in `get_looks(dist = dist, nnE = c(10, 20, 30), nnF = c(10, 20, 30))`: could not find function &quot;get_looks&quot; ('test-ocPostprob.R:27:3')">Error in `get_looks(dist = dist, nnE = c(10, 20, 30), nnF = c(10, 20, 30))`: could not find function "get_looks"</error>
    </testcase>
    <testcase time="0.037" classname="ocPostprob" name="get_decision_will_give_GO_decision_in_favourable_conditions"/>
    <testcase time="0.012" classname="ocPostprob" name="the_probability_results_of_get_oc_are_less_than_1"/>
    <testcase time="0.016" classname="ocPostprob" name="the_ExpectedN_is_within_range_based_on_vector_of_looks">
      <error type="error" message="Error in `eval(code, test_env)`: object 'all_sizes' not found ('test-ocPostprob.R:68:3')">Error in `eval(code, test_env)`: object 'all_sizes' not found
Backtrace:
    x
 1. \-checkmate::expect_number(...) at test-ocPostprob.R:68:2</error>
    </testcase>
    <testcase time="18.447" classname="ocPostprob" name="the_sum_of_Eff_Fut_Gray_zone_probabiliy_is_1"/>
    <testcase time="33.605" classname="ocPostprob" name="the_PrFutility_increases_with_increase_futility_looks"/>
    <testcase time="2.627" classname="ocPostprob" name="the_PrFutility_increases_with_increase_futility_looks"/>
    <testcase time="0.0109999999999957" classname="ocPostprob" name="the_PrFfficacy_increases_with_increase_Efficacy_looks"/>
    <testcase time="1.83" classname="ocPostprob" name="the_PrFfficacy_increases_with_increase_Efficacy_looks"/>
    <testcase time="3.631" classname="ocPostprob" name="the_PrFfficacy_increases_with_increase_Efficacy_looks">
      <failure type="failure" message="res_more_eff$oc$PrEfficacy &gt; res_more_eff$oc$PrEfficacy is not TRUE ('test-ocPostprob.R:111:3')">res_more_eff$oc$PrEfficacy &gt; res_more_eff$oc$PrEfficacy is not TRUE

`actual`:   FALSE
`expected`: TRUE </failure>
    </testcase>
    <testcase time="18.588" classname="ocPostprob" name="ocPostprob_gives_results_that_are_within_range_to_stats_pbinom"/>
    <testcase time="0.00399999999999068" classname="ocPostprob" name="ocPostprob_gives_results_that_are_within_range_to_stats_pbinom"/>
    <testcase time="18.369" classname="ocPostprob" name="ocPostprob_gives_results_that_are_within_range_to_stats_pbinom"/>
    <testcase time="0.00500000000000966" classname="ocPostprob" name="ocPostprob_gives_results_that_are_within_range_to_stats_pbinom"/>
  </testsuite>
  <testsuite name="postprob" timestamp="2023-10-11T13:24:08Z" hostname="c292e1af1db4" tests="5" skipped="0" failures="0" errors="2" time="0.074">
    <testcase time="0.012999999999991" classname="postprob" name="postprobBeta_gives_the_correct_number_result">
      <error type="error" message="Error in `postprobBeta(x = 16, n = 23, p = 0.6, a = 0.6, b = 0.4)`: could not find function &quot;postprobBeta&quot; ('test-postprob.R:4:3')">Error in `postprobBeta(x = 16, n = 23, p = 0.6, a = 0.6, b = 0.4)`: could not find function "postprobBeta"</error>
    </testcase>
    <testcase time="0.0210000000000008" classname="postprob" name="postprobBeta_gives_incrementally_higher_values_with_increase_x_support">
      <error type="error" message="Error in `postprobBeta(x = 10, n = 23, p = 0.6, a = 0.6, b = 0.4)`: could not find function &quot;postprobBeta&quot; ('test-postprob.R:9:3')">Error in `postprobBeta(x = 10, n = 23, p = 0.6, a = 0.6, b = 0.4)`: could not find function "postprobBeta"</error>
    </testcase>
    <testcase time="0.0210000000000008" classname="postprob" name="postprob_gives_the_correct_number_result"/>
    <testcase time="0.0100000000000051" classname="postprob" name="postprob_gives_the_correct_number_result"/>
    <testcase time="0.00900000000000034" classname="postprob" name="postprob_gives_incrementally_higher_values_with_increased_x"/>
  </testsuite>
</testsuites>
